apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fava-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: "managed-nfs-storage"
